name: Deploy Frequent Retrieval Stack

on:
  push:
    branches:
        - main
    paths:
        - infrastructure/**
        - .github/workflows/deploy_frequent_retrieval_stack.yml
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS Region'
        required: true
        default: 'us-east-1'
      keypair:
        description: 'SSH Key Pair'
        required: true

jobs:
  cluster:
    name: Deploy stack to AWS
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      id: creds
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::123456789100:role/my-github-actions-role
        aws-region: 'us-east-1'

    - name: Deploy Cloudformation Stack
      id: cloudformation-stack
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: frequent-retrieval-stack
        no-fail-on-empty-changeset: "1"
