name: Get Listings Info Test

on:
  push:
    branches:
      - main
      - 'feature/**'
    paths:
      - get_listings_info/**
      - .github/workflows/get_listings_info.yml
      - .github/workflows/reusable**
  pull_request:
    branches:
      - 'feature/**'

jobs:
  test-and-build:
    uses: ./.github/workflows/reusable_build_and_deploy_py_lambda.yml
    with:
      package-dir: get_listings_info
