name: Get Listings Build And Deploy

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

on:
  push:
    branches:
      - main
      - 'feature/**'
    paths:
      - get_listings/**
      - .github/workflows/get_listings.yml
      - .github/workflows/reusable**
  pull_request:
    branches:
      - 'feature/**'

jobs:
  test-and-build:
    uses: ./.github/workflows/reusable_build_and_deploy_py_lambda.yml
    with:
      package-dir: get_listings
