name: Release

permissions:
    id-token: write   # This is required for requesting the JWT
    contents: read    # This is required for actions/checkout

on:
    push:
        branches:
            - main
            - alpha

jobs:
    # test:
    #     name: Test and lint
    #     uses: ./.github/workflows/development.yml

    # docker:
    #     name: Build Docker Images
    #     runs-on: ubuntu-latest
    #     strategy:
    #         matrix:
    #           package:
    #             - path: get_tickers
    #               repo: GetTickersLambdaRepo
    #     steps:
    #         - name: Login to Amazon ECR Public
    #           id: login-ecr-public
    #           uses: aws-actions/amazon-ecr-login@v1
    #           with:
    #             mask-password: 'true'
    #             registry-type: public

    #         - name: Build, tag, and push docker image to Amazon ECR Public
    #           env:
    #             REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
    #             REGISTRY_ALIAS: my-ecr-public-registry-alias
    #             REPOSITORY: ${{ matrix.package.repo }}
    #             IMAGE_TAG: ${{ github.sha }}
    #           run: |
    #             cd lambda/${{ matrix.package.path }}
    #             docker build -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG .
    #             docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG

    cloud-formation:
        name: Deploy CloudFormation Stacks
        runs-on: ubuntu-latest
        defaults:
            run:
              working-directory: infrastructure
        steps:
            - name: "checkout repository"
              uses: actions/checkout@v2
            - name: "setup node"
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: "install dependencies"
              run: |
                npm install -g aws-cdk
                npm install
            - name: "build"
              run: npm run build
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: arn:aws:iam::025257542471:role/github_oidc_role
                aws-region: us-east-1
            - name: CDK Synth
              run: cdk synth *
            - name: CDK Deploy
              run: cdk deploy *