name: State Machine Test and Deploy

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

on:
  push:
    branches:
      - main
      - 'feature/**'
    paths:
      - state_machine/**
      - .github/workflows/state_machine.yml
  pull_request:
    branches:
      - 'feature/**'

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
      - name: Setup Docker
        run: |
          docker pull amazon/aws-stepfunctions-local
          docker run -p 8083:8083 amazon/aws-stepfunctions-local
      - name: Run Local Execution
        run: |
          python prepare_mock_config.py
          make docker
          make create-sm
          make exec-happypath
          sleep 300s
          make get-results
          make test
      - name: Configure AWS credentials
        if: github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::025257542471:role/github_oidc_role
          aws-region: us-east-1
      - name: Deploy to StepFunctions
        if: github.ref == 'refs/heads/main'
        run: |
          cd state_machine
          aws stepfunctions update-state-machine --state-machine-arn arn:aws:states:us-east-1:025257542471:stateMachine:DataRetrieval --definition file://data_retrieval.json
