name: State Machine Test and Deploy

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

on:
  push:
    branches:
      - main
      - 'feature/**'
    paths:
      - state_machine/**
      - .github/workflows/state_machine.yml
  pull_request:
    branches:
      - 'feature/**'

env:
  SFN_MOCK_CONFIG: data_retrieval_mock_config.json
  AWS_REGION: us-east-1

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: state_machine
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      ### Setup For Testing and Deploying
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Download StepFunctionsLocal Jar
        run: |
          wget https://s3.amazonaws.com/stepfunctionslocal/StepFunctionsLocal.zip
          unzip StepFunctionsLocal.zip
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::025257542471:role/github_oidc_role
          aws-region: us-east-1

      ### Testing
      - name: Prepare Mock Config
        run: python prepare_mock_config.py
      - name: Run StepFunctions Local
        run: |
          java -jar StepFunctionsLocal.jar &
      - name: Run Local Execution
        run: |
          make create-sm
          make exec-happypath
          sleep 300s
          make get-results
          make test

      ### Deploying
      - name: Deploy to StepFunctions
        if: github.ref == 'refs/heads/main'
        run: |
          aws stepfunctions update-state-machine --state-machine-arn arn:aws:states:us-east-1:025257542471:stateMachine:DataRetrieval --definition file://data_retrieval.json
